### PR TITLE
Make python3 compatible

### PR DESCRIPTION
**Pull request by quazgar**
Made the code compatible with python3 (also tested with 2.7, should work with 2.6), also made the histogram check for different bit resolutions and sample rates optional.

Plus small changes to the README.

### CODE REVIEW

**Comment by quazgar** [comment]
Yes, you are right about the `simple_layout`.  If necessary, we can split this up into different pull requests.
It was actually one of the first things we did to the code because we typically deal with a few GB of acq data.

**Comment by quazgar** [comment]
Additional comment: The string test in `AcqReader.read_file(cls, filelike)` currently fails for unicode strings. Is using six a problem for you to do this test for both 2.x and 3?  If not, I would use http://stackoverflow.com/a/20612311/232888 instead.

**Comment by njvack** [comment]
Six would be great. It's worth checking to see if there's anywhere else I've been assuming non-unicode strings :neutral_face:

**Comment by quazgar** [comment]
Closed this pull request in favor of the other two which I just created.  There should be no changes between the other two combined and our master.

**Pull request closed without merging**
